### ISSUE TITLE
Some of these aren't states or territories - they're entirely different countries

### ISSUE THREAD

**Issue by petebarnettio** [scriptex/typed-usa-states#118]
The following are countries unaffiliated with the United States (via state, incorporated territory, or unincorporated territory) and should be removed. They are part of **Compacts of Free Association**, but are separate entities entirely, maintaining embassies in the United States. To have them under a list of "typed-usa-states" is extremely misleading.

- Federated States of Micronesia
- Marshall Islands
- Palau

**Comment by scriptex** [comment]
Thanks for the input @petebarnettio . Do you think you will have the time to remove them by submitting a PR?

**Comment by scriptex** [comment]
@petebarnettio I've took the time to update this. The new version (2.1.0) is available [on Github](https://github.com/scriptex/typed-usa-states/releases/tag/2.1.0) and [on NPM](https://www.npmjs.com/package/typed-usa-states). 

Thank you for your contribution!

**Comment by petebarnettio** [comment]
Great work, thanks @scriptex!
